### ISSUE TITLE
List of Configuration Tags Missing

### ISSUE THREAD

**Issue by ghost** [krisxoofoo/Pagemap-ImageWall#2]
Hello,

It would appear that the website hosting all of the configuration options, getpagemap.com, no longer exists. Can you please provide a complete list of config options in the readme?

Thank you.

**Comment by krisxoofoo** [comment]
config.in in root, ex:

[Author: John Doe]
[Gallery Title: My Pagemap ImageWall Gallery Demo]
[Gallery Description: Pagemap ImageWall Gallery adapted by XooFoo]
[Meta Keywords: gallery, photos, holidays, mobile]
[Thumbnail Cropped: on]
[Thumbnail Quality: 80]
[Thumbnail Size: normal]
[Thumbnail Background: black]
[Controls Image: black]
[Image Size: ]
[Sort: normal]
[Embedded Script: off]
[Other JS: js/twitter.js]
[ImageWall Width: 900px]
[Header Image: img/logo.png]
[Background: white]
[Header Color: silver]
[Content Color: black]
[Footer Color: silver]
[Custom CSS: ]
[Custom FileCSS: css/style.css]
[Custom HTML:<section id="social"><p><iframe src="github-btn.html?user=krisxoofoo&repo=Pagemap-ImageWall-Gallery&type=fork&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="84px" height="20px"></iframe><iframe src="github-btn.html?user=krisxoofoo&repo=Pagemap-ImageWall-Gallery&type=watch&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="84px" height="20px"></iframe><iframe src="github-btn.html?user=krisxoofoo&type=follow&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="284px" height="20px"></iframe><a href="https://twitter.com/kris_fr" class="twitter-follow-button" data-show-count="false">Follow @kris_fr</a></p></section><section class="download"><a rel="tooltip" href="https://github.com/krisxoofoo/Pagemap-ImageWall-Gallery/zipball/master" class="primary btn" title="Download Pagemap ImageWall Gallery on GitHub">Download on GitHub</a></section>]
[Home Page: http://test.xoofoo.org/pagemapgallery/]
[Contact: johndoe@lolilop.me]
[Imprint: ]
[Images Dir: /foldergallery]
[Images List: ]
[Exclude Images: ]
[Disqus Shortname: myshortnamedisqus]
[GoogleAnalytics Account: ]
[Per Page: 15]
